version: '3'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/src:/var/www/html
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app
    ports:
      - "4200:4200"
    networks:
      - app-network

  database:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  webserver:
    build:
      context: ./webserver
    ports:
      - "8080:80"
    volumes:
      - ./backend/src:/var/www/html
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
